spring.application.name=demo
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.mail=DEBUG
spring.mail.properties.mail.debug=true
spring.jpa.hibernate.ddl-auto=create

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abutodzn@gmail.com
spring.mail.password=cuvhxmgyuewgkaow 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

api.security.token.secret=projeto-open-inventory-2026